---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates on Ubuntu
    tags: always
    package:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install updates on Rocky
    tags: always
    package:
      update_cache: true
      update_only: true
    when: ansible_distribution == "Rocky"

- hosts : web_servers
  become: true
  tasks:

  - name: install apache and php packages on Ubuntu
    tags: apache,apache2,php,ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages on Rocky
    tags: apache,apache2,php,rocky
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package on Ubuntu
    tags: db,mariadb,ubuntu
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb on Rocky
    tags: db,mariadb,rocky
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba,ubuntu,rocky
    package:
      name: samba
      state: latest

  